🚀Production Release (#79)
* Update KinsonDigital/Infrastructure action to v14.3.0 (#61)

| datasource  | package                      | from    | to      |
| ----------- | ---------------------------- | ------- | ------- |
| github-tags | KinsonDigital/Infrastructure | v14.2.0 | v14.3.0 |

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* 🚧Improve kd admin tool (#71)

* Start work for issue #70

* cleanup: remove unused regex

removes unused feature branch regex from utils class to
simplify the codebase and improve maintainability.

ide: update launch configurations for debugging

updates launch configurations by removing and adding
arguments to improve the debugging experience and adds
dependencies to the deno.lock file.

* chore: further improvements

1. Add ability to choose which job to run
2. Improve git command error processing
3. Create func to check if a github issue exists.

* test: update branch name validation regex

updates branch name validation regex to allow only
letters, spaces, hyphens, or underscores and adds a
transform function to format the branch name.

* feat: Added GitHub PR creation and models.

This change introduces the ability to create GitHub pull requests programmatically. It also adds new data models to represent GitHub entities like labels, milestones, repos, users and pull requests.

* feat: add jobs option to supply a job name with the command.

* chore: update imports to use alias

* ide: add word to dictionary

* refactor: improve types

* chore: make further improvements

* chore: remove install and update scripts

* docs: update readme

* refactor: adjust imports to meet coding standards

* fix: fix errors due to update of kdclients package

* refactor: improve code to meet coding standards

* config: setup deno.json file to publish to jsr

* deps: update deno lock

* ci: update release workflow

1. Set up better github release creation
2. Add step to publish to jsr
3. Add better workflow validation checks

* ci: update checkout action to v5

* fix: fix error in playground module

* ci: remove pr/issue sync workflows

* ci: update setup deno action to v2

* ide: add word to dictionary

* Update infrastructure (#77)

* Start work for issue #76

* refactor: change name of utils module file name

* ci: remove sync workflow

* ci: improve status checks and setup deno caching

* ci: improve release workflow by using new infrastructure actions

* config: remove kd admin tool as a dev tool

* config: setup create pr and generate release notes dev tools

* pr-review: remove unused powershell variable

* Rename project to prepare for release to jsr (#78)

* Start work for issue #75

* chore: rename all old project refs to the new project name

* config: fix deno task for tests and test status check

* pr-review: fix small issues

* test: fix test status check workflow trigger

* refactor: rename file

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,10 +11,10 @@ on:
   workflow_dispatch:
     inputs:
       release-type:
-        description: The type of release.  Choose 'Preview' or 'Production'.
+        description: The type of release.  Choose 'Production' or 'Preview'.
         required: true
         type: choice
-        options: [Preview, Production]
+        options: [Production, Preview]
       dry-run:
         required: false
         description: Dry Run (if true, the release will not be created)
@@ -23,160 +23,246 @@ on:
 
 
 jobs:
-  get_version:
-    name: Get Version
+  get_and_validate_version:
+    name: Get And Validate Version
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.get_version.outputs.version }}
+      version: ${{ steps.get-version.outputs.version }}
     steps:
-      - name: Setup Deno
-        uses: denoland/setup-deno@v1
-        with:
-          deno-version: ${{ vars.DENO_VERSION }}
-
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
       - name: Get Version
-        id: get_version
-        working-directory: ${{ github.workspace }}
-        run: |
-          $scriptPath = "${{ github.workspace }}/.github/cicd/scripts/get-version.ts";
-
-          deno run -R -W -E "$scriptPath";
-
-
-  validate_release:
-    name: Validate Workflow Inputs
-    runs-on: ubuntu-latest
-    needs: get_version
-    steps:
-      - name: Validate Workflow Inputs
-        run: |
-          $branch = "${{ github.ref }}".TrimStart('refs/heads/');
-          $expectedPrevBranch = "${{ vars.PREV_RELEASE_BRANCH }}".Trim();
-          $expectedProdBranch = "${{ vars.PROD_RELEASE_BRANCH }}".Trim();
-
-          if ($expectedPrevBranch -eq "") {
-            Write-Host "::error::The PREV_RELEASE_BRANCH variable is not set.";
-            exit 1;
-          }
-
-          if ($expectedProdBranch -eq "") {
-            Write-Host "::error::The PROD_RELEASE_BRANCH variable is not set.";
-            exit 1;
-          }
-
-          if ($branch -ne $expectedPrevBranch -and $branch -ne $expectedProdBranch) {
-            Write-Host "::error::Releases are only allowed to be run on '$expectedPrevBranch' or '$expectedProdBranch' branches.";
-            exit 0; # TODO: THIS NEEDS TO BE CHANGED TO 1 WHNE FINISHED WITH DEBUGGING
-          }
-
-      - name: Setup Deno
-        uses: denoland/setup-deno@v1
+        id: get-version
+        uses: KinsonDigital/Infrastructure/actions/get-version@v16.0.0
         with:
-          deno-version: ${{ vars.DENO_VERSION }}
+          version-file-path: "${{ github.workspace }}/deno.json"
+          deno-version: "${{ vars.DENO_VERSION }}"
+          json-prop-path: "version"
+
+      - name: Validate Version
+        id: validate-version
+        uses: KinsonDigital/Infrastructure/actions/validate-version@v16.0.0
+        with:
+          version: "${{ steps.get-version.outputs.version}}"
+          release-type: "${{ inputs.release-type }}"
+          deno-version: "${{ vars.DENO_VERSION }}"
+
+
+  run_prerelease_validation:
+    name: Run Pre-Release Validation
+    needs: [get_and_validate_version]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Branch
+        id: check-branch
+        continue-on-error: true
+        run: |
+          if ("${{ github.ref_name }}" -ne "main") {
+            exit 1;
+          }
 
       - name: Checkout Repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
-      - name: Version Does Not Exist
-        env:
-          OWNER_NAME: "${{ vars.ORGANIZATION_NAME }}"
-          REPO_NAME: "${{ vars.PROJECT_NAME }}"
-          VERSION_TYPE: "${{ inputs.release-type }}"
-          VERSION: "${{ needs.get_version.outputs.version }}"
-          GITHUB_TOKEN: "${{ secrets.CICD_TOKEN }}"
+      - name: Set Up Deno (${{ vars.DENO_VERSION }})
+        uses: denoland/setup-deno@v2
+        with:
+          deno-version: ${{ vars.DENO_VERSION }}
+          cache: true
+
+      - name: Milestone Exists
+        id: milestone-exists
+        uses: KinsonDigital/Infrastructure/actions/milestone-exists@v16.0.0
+        with:
+          owner-name: "${{ vars.ORGANIZATION_NAME }}"
+          repo-name: "${{ vars.PROJECT_NAME }}"
+          milestone-name: "v${{ needs.get_and_validate_version.outputs.version }}"
+          github-token: "${{ secrets.CICD_TOKEN }}"
+          deno-version: "${{ vars.DENO_VERSION }}"
+
+      - name: Validate Milestone Items
+        id: milestone-items-check
+        uses: KinsonDigital/Infrastructure/actions/milestone-items-closed@v16.0.0
+        with:
+          owner-name: "${{ vars.ORGANIZATION_NAME }}"
+          repo-name: "${{ vars.PROJECT_NAME }}"
+          milestone-name: "v${{ needs.get_and_validate_version.outputs.version }}"
+          github-token: "${{ secrets.CICD_TOKEN }}"
+          deno-version: "${{ vars.DENO_VERSION }}"
+          fail-if-all-items-not-closed: true
+        continue-on-error: false
+
+      - name: JSR Package Exists
+        id: jsr-package-exists
+        uses: KinsonDigital/Infrastructure/actions/jsr-pkg-exists@v16.0.0
+        with:
+          scope: "${{ vars.JSR_SCOPE }}"
+          pkg-name: "${{ vars.JSR_SCOPE }}"
+          version: "${{ needs.get_and_validate_version.outputs.version }}"
+          deno-version: "${{ vars.DENO_VERSION }}"
+          fail-if-exists: true
+        continue-on-error: true
+
+      - name: Lowercase Release Type
+        id: release-type
         run: |
-          $scriptPath = "${{ github.workspace }}/.github/cicd/scripts/version-checker.ts";
-
-          deno run `
-          -E `
-          -N `
-          --allow-run "$scriptPath";
+          $releaseType = "${{ inputs.release-type }}".ToLower();
+          "release-type=$releaseType" > "$env:GITHUB_OUTPUT";
 
       - name: Release Notes Exist
-        env:
-          RELEASE_TYPE: "${{ inputs.release-type }}"
-          VERSION: "${{ needs.get_version.outputs.version }}"
-        run: |
-          $scriptPath = "${{ github.workspace }}/.github/cicd/scripts/check-release-notes.ts";
+        id: release-notes-check
+        uses: KinsonDigital/Infrastructure/actions/release-notes-exist@v16.0.0
+        with:
+          release-notes-file-path: "${{ github.workspace }}/release-notes/${{ steps.release-type.outputs.release-type }}-releases/Release-Notes-v${{ needs.get_and_validate_version.outputs.version }}.md"
+          deno-version: "${{ vars.DENO_VERSION }}"
+          fail-if-does-not-exist: true
+        continue-on-error: true
 
-          deno run -E -R "$scriptPath";
+      - name: GitHub Release Exists
+        id: github-release-check
+        uses: KinsonDigital/Infrastructure/actions/github-release-exists@v16.0.0
+        with:
+          owner-name: "${{ vars.ORGANIZATION_NAME }}"
+          repo-name: "${{ vars.PROJECT_NAME }}"
+          tag-name: "v${{ needs.get_and_validate_version.outputs.version }}"
+          deno-version: "${{ vars.DENO_VERSION }}"
+          github-token: "${{ secrets.CICD_TOKEN }}"
+        continue-on-error: true
+    
+      - name: Should Fail Job
+        run: |
+          $validBranch = "${{ steps.check-branch.outcome == 'failure' }}";
+          $milestoneExists = "${{ steps.milestone-exists.outputs.milestone-exists }}";
+          $milestoneItemsCheckFailed = "${{ steps.milestone-items-check.outcome == 'failure' }}";
+
+          $jsrPkgExists = "${{ steps.jsr-package-exists.outcome == 'failure' }}";
+
+          $releaseNotesCheckFailed = "${{ steps.release-notes-check.outcome == 'failure' }}";
+          $githubReleaseCheckFailed = "${{ steps.github-release-check.outcome == 'failure' }}";
+
+          if ($validBranch -eq "true") {
+            Write-Host "::error::The branch '${{ github.ref_name }}' is invalid.  Must run on the 'main' branch.";
+          }
+
+          if ($milestoneExists -eq "false") {
+            Write-Host "::error::The milestone '${{ needs.get_and_validate_version.outputs.version }}' does not exist.";
+          }
+
+          if ($milestoneItemsCheckFailed -eq "true") {
+            Write-Host "::error::The milestone '${{ needs.get_and_validate_version.outputs.version }}' has one or more issues that are not closed or prs that are in draft.";
+          }
+          
+          if ($jsrPkgExists -eq "true") {
+            Write-Host "::error::The JSR package '${{ vars.JSR_PACKAGE_NAME }}' for version '${{ needs.get_and_validate_version.outputs.version }}' already exists.";
+          }
+
+          if ($releaseNotesCheckFailed -eq "true") {
+            Write-Host "::error::The release notes do not exist.";
+          }
+
+          if ($githubReleaseCheckFailed -eq "true") {
+            Write-Host "::error::The GitHub release already exists.";
+          }
+
+          if ($validBranch -eq "true" `
+              -or $milestoneExists -eq "false" `
+              -or $milestoneItemsCheckFailed -eq "true" `
+              -or $jsrPkgExists -eq "true" `
+              -or $releaseNotesCheckFailed -eq "true" `
+              -or $githubReleaseCheckFailed -eq "true") {
+            exit 1;
+          }
 
 
   release:
     name: Run ${{ inputs.release-type }} Release
     runs-on: ubuntu-latest
-    needs: [get_version, validate_release]
+    needs: [get_and_validate_version, run_prerelease_validation]
+    permissions:
+      id-token: write # The OIDC ID token is used for authentication with JSR.
     steps:
-      - name: Setup Deno
-        uses: denoland/setup-deno@v1
+      - name: Set Up Deno (${{ vars.DENO_VERSION }})
+        uses: denoland/setup-deno@v2
         with:
           deno-version: ${{ vars.DENO_VERSION }}
+          cache: true
 
       - name: Checkout Repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Run Check
+        id: deno-check
+        continue-on-error: true
         run: deno check **/*/*.ts;
 
       - name: Run Lint
-        run: deno lint
+        id: deno-lint
+        continue-on-error: true
+        run: deno lint **/*.ts;
+
+      - name: Deno Format
+        id: deno-format
+        continue-on-error: true
+        run: deno fmt --check ./**/*.ts;
 
       - name: Run Tests
-        run: deno test -R ./tests/*Tests.ts;
+        id: deno-tests
+        continue-on-error: true
+        run: deno test -R ./tests/*tests.ts;
 
-      - name: Create GitHub Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
-        if: ${{ inputs.dry-run == false }}
-        env:
-          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
+      - name: Validate Checks ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
         run: |
-          $ownerRepoName = "${{ github.repository }}";
+          $lintFailed = "${{ steps.deno-lint.outcome }}" -eq "failure";
+          $formatFailed = "${{ steps.deno-format.outcome }}" -eq "failure";
+          $checkFailed = "${{ steps.deno-check.outcome }}" -eq "failure";
+          $testsFailed = "${{ steps.deno-tests.outcome }}" -eq "failure";
 
-          $tag = "${{ needs.get_version.outputs.version }}".ToLower().Trim();
-          $tag = $tag.StartsWith("v") ? $tag : "v$tag";
+          if ($lintFailed) {
+            Write-Host "::error::The lint check has failed.";
+          }
 
-          $releaseType = "${{ inputs.release-type }}";
-          $version = "${{ needs.get_version.outputs.version }}";
+          if ($formatFailed) {
+            Write-Host "::error::The format has failed.";
+          }
 
-          $title = "$releaseType Release - $version";
+          if ($checkFailed) {
+            Write-Host "::error::The check has failed.";
+          }
 
-          $releaseDirPrefix = $releaseType.ToLower();
-          $releaseTypeDir = "$releaseDirPrefix-releases";
-          $fullReleaseNotesPath = "${{ github.workspace }}/release-notes/$releaseTypeDir/Release-Notes-${{ needs.get_version.outputs.version }}.md";
+          if ($testsFailed) {
+            Write-Host "::error::The tests have failed.";
+          }
 
-          $isPreRelease = $releaseType -eq "Preview" ? "--prerelease" : "";
+          if ($lintFailed -or $formatFailed -or $checkFailed -or $testsFailed) {
+            exit "${{ inputs.dry-run }}" -eq "true" ? 0 : 1;
+          }
 
-          Write-Host "::notice::Release Notes File Path: $fullReleaseNotesPath";
+      - name: Publish To JSR ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
+        if: inputs.dry-run == false
+        run: deno publish;
 
-          gh release create $tag `
-            -R $ownerRepoName `
-            --target ${{ github.ref_name }} `
-            -t $title `
-            -F $fullReleaseNotesPath `
-            $isPreRelease `
-            $fullReleaseNotesPath;
-
-      - name: Close Milestone ${{ needs.get_version.outputs.version }}
-        if: ${{ inputs.dry-run == false }}
+      - name: Lowercase Release Type
+        id: release-type
         run: |
-          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
-          $scriptUrl = $scriptUrl.Replace("\", "/").Replace("//", "/");
-          $scriptUrl = $scriptUrl.EndsWith("/") ? $scriptUrl.Substring(0, $scriptUrl.Length - 1) : $scriptUrl;
-          $scriptUrl = "$scriptUrl/close-milestone.ts";
+          $releaseType = "${{ inputs.release-type }}".Trim().ToLower();
+          "release-type=$releaseType" >> $env:GITHUB_OUTPUT;
 
-          Write-Host "::notice::Close milestone script URL: $scriptUrl";
+      - name: Creating ${{ inputs.release-type }} GitHub Release
+        if: inputs.dry-run == false
+        uses: softprops/action-gh-release@v2
+        with: 
+          name: "🚀${{ inputs.release-type }} Release - ${{ needs.get_and_validate_version.outputs.version }}" 
+          body_path: "${{ github.workspace }}/release-notes/${{ steps.release-type.outputs.release-type }}-releases/Release-Notes-v${{ needs.get_and_validate_version.outputs.version }}.md"
+          files: "${{ github.workspace }}/release-notes/${{ steps.release-type.outputs.release-type }}-releases/Release-Notes-v${{ needs.get_and_validate_version.outputs.version }}.md"
+          tag_name: "v${{ needs.get_and_validate_version.outputs.version }}"
+          prerelease: ${{ inputs.release-type == 'Preview' }}
+          draft: false
+          token: "${{ secrets.CICD_TOKEN }}"
 
-          <# Deno Args:
-            1. Project name
-            2. Milestone name - This is the version
-            3. PAT
-          #>
-          deno run `
-            -R `
-            -N `
-            "$scriptUrl" `
-            "${{ vars.PROJECT_NAME }}" `
-            "${{ needs.get_version.outputs.version }}" `
-            "${{ secrets.CICD_TOKEN }}";
+      - name: Close Milestone ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
+        if: inputs.dry-run == false
+        uses: KinsonDigital/Infrastructure/actions/close-milestone@v16.0.0
+        with:
+          repo-owner: "${{ vars.ORGANIZATION_NAME }}"
+          repo-name: "${{ vars.PROJECT_NAME }}"
+          github-token: "${{ secrets.CICD_TOKEN }}"
+          milestone-title: "${{ needs.get_and_validate_version.outputs.version }}"
+          deno-version: "${{ vars.DENO_VERSION }}"
